// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "0.1.79",
    buildId: "20260709-215400Z",
    builtAt: "2026-07-09T21:54:00.341Z"
  };
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;

  // Dev config overrides (injected at build time)
  window.__PLAYER_CONFIG__ = {
    API_BASE: "https://screenhub.900.ca/api/v1",
    WS_URL: "wss://screenhub.900.ca",
    COMPANY_NAME: "900"
  };
})();
