// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "0.1.59",
    buildId: "20260509-234135Z",
    builtAt: "2026-05-09T23:41:35.127Z"
  };
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;

  // Dev config overrides (injected at build time)
  window.__PLAYER_CONFIG__ = {
    API_BASE: "http://192.168.1.17/api/v1",
    WS_URL: "ws://192.168.1.17"
  };
})();
