// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "0.1.0",
    buildId: "20260507-185436Z",
    builtAt: "2026-05-07T18:54:36.593Z"
  };
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;
})();
