packages:
  - 'apps/*'
  - '!apps/tizen'
  - '!apps/tizen-sbb'
  - '!apps/test-nodejs-mdc-sbb'
  - 'packages/*'

allowBuilds:
  argon2: true
  core-js: true
  electron: false
  esbuild: true
  msgpackr-extract: true
  sharp: true
