packages:
  - 'apps/*'
  - '!apps/tizen'
  - '!apps/tizen-sbb'
  - '!apps/test-nodejs-mdc-sbb'
  - 'packages/*'

neverBuiltDependencies:
  - electron

onlyBuiltDependencies:
  - argon2
  - core-js
  - esbuild
  - msgpackr-extract
  - sharp
