// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "1.0.62",
    buildId: "20260511-025828Z",
    builtAt: "2026-05-11T02:58:28.656Z"
  };

  // Exposed for debugging in Remote Inspector
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;

  // Dev config overrides (injected at build time)
  window.__PLAYER_CONFIG__ = {
    API_BASE: "https://ds.chiho.app/api/v1",
    WS_URL: "wss://ds.chiho.app"
  };
})();
