// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "1.0.205",
    buildId: "20260720-130743Z",
    builtAt: "2026-07-20T13:07:43.390Z"
  };

  // Exposed for debugging in Remote Inspector
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;

  // Dev config overrides (injected at build time)
  window.__PLAYER_CONFIG__ = {
    API_BASE: "https://ct.reflowcast.com/api/v1",
    WS_URL: "wss://ct.reflowcast.com",
    COMPANY_NAME: "reflowcast"
  };
})();
