// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "1.0.147",
    buildId: "20260620-012115Z",
    builtAt: "2026-06-20T01:21:15.865Z"
  };

  // Exposed for debugging in Remote Inspector
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;

  // Dev config overrides (injected at build time)
  window.__PLAYER_CONFIG__ = {
    API_BASE: "https://platform.nexari.ca/api/v1",
    WS_URL: "wss://platform.nexari.ca"
  };
})();
