plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Load keystore.properties (generated by deploy-android.ps1, not committed to git)
val keystorePropsFile = rootProject.file("keystore.properties")
val keystoreMap: Map<String, String> = if (keystorePropsFile.exists()) {
    keystorePropsFile.readLines()
        .filter { it.contains("=") && !it.trimStart().startsWith("#") }
        .associate { line ->
            val idx = line.indexOf('=')
            line.substring(0, idx).trim() to line.substring(idx + 1).trim()
        }
} else {
    emptyMap()
}
android {
    namespace = "app.chiho.nexari"
    compileSdk = 34

    defaultConfig {
        applicationId = "app.chiho.nexari"
        minSdk = 24
        targetSdk = 34
        versionCode = 122
        versionName = "0.1.22"

        // Manifest-wide opt-in is now off; res/xml/network_security.xml is the
        // single source of truth and permits HTTP only to whitelisted LAN hosts
        // (192.168.1.17, 10.0.2.2, localhost, 127.0.0.1). Production traffic to
        // Production traffic is HTTPS-only to the configured platform host.
        manifestPlaceholders["usesCleartextTraffic"] = "false"
    }

    signingConfigs {
        if (keystoreMap.isNotEmpty()) {
            create("release") {
                storeFile = file(keystoreMap["storeFile"]!!)
                storePassword = keystoreMap["storePassword"]!!
                keyAlias = keystoreMap["keyAlias"]!!
                keyPassword = keystoreMap["keyPassword"]!!
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (keystoreMap.isNotEmpty()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
        getByName("debug") {
            isMinifyEnabled = false
        }
    }

    flavorDimensions += "channel"
    productFlavors {
        // Dev build â€” points at LAN nginx on 192.168.1.17:80 (same as Tizen build:dev).
        // nginx proxies / to 127.0.0.1:3000 and upgrades WS automatically.
        create("dev") {
            dimension = "channel"
            buildConfigField("boolean", "OTA_ENABLED", "false")
            buildConfigField("String",  "DEFAULT_API_BASE", "\"http://192.168.1.17/api/v1\"")
            buildConfigField("String",  "DEFAULT_WS_BASE",  "\"ws://192.168.1.17\"")
            buildConfigField("String",  "DEFAULT_OTA_URL",  "\"\"")
        }
        // Self-hosted APK with in-app OTA enabled.
        // For partner builds, pass -PpartnerApiBase and -PpartnerWsBase to Gradle.
        create("self") {
            dimension = "channel"
            val partnerApi = (project.findProperty("partnerApiBase") as String?)
                ?: ""
            val partnerWs = (project.findProperty("partnerWsBase") as String?)
                ?: ""
            val otaBase = partnerApi.removeSuffix("/api/v1")
            buildConfigField("boolean", "OTA_ENABLED", "true")
            buildConfigField("String",  "DEFAULT_API_BASE", "\"$partnerApi\"")
            buildConfigField("String",  "DEFAULT_WS_BASE",  "\"$partnerWs\"")
            buildConfigField("String",  "DEFAULT_OTA_URL",  "\"$otaBase/android/update.json\"")
        }
        // Google Play / Managed Play â€” Play handles updates.
        create("play") {
            dimension = "channel"
            buildConfigField("boolean", "OTA_ENABLED", "false")
            buildConfigField("String",  "DEFAULT_API_BASE", "\"\"")
            buildConfigField("String",  "DEFAULT_WS_BASE",  "\"\"")
            buildConfigField("String",  "DEFAULT_OTA_URL",  "\"\"")
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    packaging {
        resources.excludes += setOf("META-INF/AL2.0", "META-INF/LGPL2.1")
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.activity:activity-ktx:1.9.0")
    implementation("androidx.webkit:webkit:1.11.0")
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.2")
    implementation("androidx.lifecycle:lifecycle-process:2.8.2")
    implementation("androidx.work:work-runtime-ktx:2.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
    implementation("com.google.code.gson:gson:2.11.0")
}






















