$src   = "C:\Users\chiho\Projects\Platform\apps\nexari-tizen"
$tizen = "C:\tizen-studio\tools\ide\bin\tizen.bat"
$sdb   = "C:\tizen-studio\tools\sdb.exe"
$tv    = "192.168.1.11:26101"
$appId = "fmDBbBnvJM.NexariTizen"
$pi    = "chiho@192.168.1.17"
$tmp   = "$env:TEMP\nexari-tizen-build"

# --- 1. BUILD ---
Write-Host "=== STEP 1: Build ==="

if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }
New-Item $tmp -ItemType Directory | Out-Null

$excludeNames = @(
    'node_modules', 'src', '.sign', '.settings',
    '.project', '.tproject', '.git',
    'vite.config.ts', 'package-lock.json', 'sssp_config.xml'
)
foreach ($item in Get-ChildItem $src) {
    if ($excludeNames -contains $item.Name) { continue }
    if ($item.Extension -eq '.wgt') { continue }
    if ($item.Name -eq '.manifest.tmp') { continue }
    if ($item.PSIsContainer) {
        Copy-Item $item.FullName "$tmp\$($item.Name)" -Recurse
    } else {
        Copy-Item $item.FullName $tmp
    }
}

Write-Host "Staging dir: $((Get-ChildItem $tmp -Recurse -File).Count) files"
Remove-Item "$src\*.wgt" -ErrorAction SilentlyContinue

# Run build:dev to regenerate build-info.js with LAN API URL (Pi at 192.168.1.17)
Write-Host "Running npm run build:dev..."
Push-Location $src
try {
    npm run build:dev 2>&1 | Write-Host
    if ($LASTEXITCODE -ne 0) { throw "npm run build:dev failed" }
} finally {
    Pop-Location
}

# Re-copy all compiled js/ output (regenerated by build:dev via tsc)
Copy-Item "$src\js" "$tmp\js" -Recurse -Force

Write-Host "Packaging with testforqbc profile..."
& $tizen package --type wgt --sign testforqbc -o $src -- $tmp 2>&1

$wgt = Get-ChildItem $src -Filter "*.wgt" | Select-Object -First 1
if (-not $wgt) {
    Write-Error "Build failed - no WGT produced. Aborting."
    exit 1
}
if ($wgt.Name -ne "NexariPlayer.wgt") {
    Rename-Item $wgt.FullName "$src\NexariPlayer.wgt" -Force
    Write-Host "Renamed $($wgt.Name) -> NexariPlayer.wgt"
}
$sizeKB = [math]::Round((Get-Item "$src\NexariPlayer.wgt").Length / 1KB)
Write-Host "WGT size: ${sizeKB} KB"

# Update sssp_config.xml with the exact byte-size so Tizen SSSP devices can
# verify the download before installing.
# IMPORTANT: Use explicit UTF-8 to avoid double-encoding corruption.
$wgtBytes   = (Get-Item "$src\NexariPlayer.wgt").Length
$ssspConfig = "$src\sssp_config.xml"
$ssspXml = [System.IO.File]::ReadAllText($ssspConfig, [System.Text.UTF8Encoding]::new($false))
$ssspXml = $ssspXml -replace '<size>\d+</size>', "<size>$wgtBytes</size>"
[System.IO.File]::WriteAllText($ssspConfig, $ssspXml, [System.Text.UTF8Encoding]::new($false))
Write-Host "Updated sssp_config.xml <size> to $wgtBytes bytes"

# --- 1c. DEPLOY TO PI SERVER ---
Write-Host ""
Write-Host "=== STEP 1c: Deploy WGT to Pi server ($pi) ==="
$piTizenDir = "/var/signage/tizen"
scp "$src\NexariPlayer.wgt" "${pi}:${piTizenDir}/NexariPlayer.wgt"
if ($LASTEXITCODE -ne 0) { Write-Warning "WGT SCP failed - check SSH access to $pi" }
scp "$src\sssp_config.xml" "${pi}:${piTizenDir}/sssp_config.xml"
if ($LASTEXITCODE -ne 0) { Write-Warning "sssp_config.xml SCP failed" }
Write-Host "Pi server updated: http://192.168.1.17/tizen/NexariPlayer.wgt"

# --- 1b. SDB CONNECT ---
Write-Host ""
Write-Host "=== STEP 1b: SDB Connect ==="
$connectOut = & $sdb connect $tv 2>&1 | Out-String
Write-Host $connectOut
if ($connectOut -notmatch "connected to|already connected") {
    Write-Host "WARNING: sdb connect may have failed. Check TV Developer Mode is on and IP is correct." -ForegroundColor Yellow
}
Start-Sleep -Seconds 2

# --- 2. UNINSTALL ---
Write-Host ""
Write-Host "=== STEP 2: Uninstall ==="
foreach ($pkg in @($appId, "yhSyDyxfkq.NexariPlayer", "q6naPUaTRW.NexariPlayer")) {
    Write-Host "Removing $pkg ..."
    & $tizen uninstall -s $tv -p $pkg 2>&1 | Out-String | Write-Host
}
Start-Sleep -Seconds 3

# --- 3. INSTALL ---
Write-Host ""
Write-Host "=== STEP 3: Install ==="
& $tizen install -s $tv -n NexariPlayer.wgt -- $src 2>&1

# --- 4. LAUNCH ---
Write-Host ""
Write-Host "=== STEP 4: Launch ==="
Start-Sleep -Seconds 2
& $tizen run -s $tv -p $appId 2>&1 | Out-String | Write-Host
