$src    = "C:\Users\chiho\Projects\Platform\apps\nexari-tizen"
$tizen  = "C:\tizen-studio\tools\ide\bin\tizen.bat"
$sdb    = "C:\tizen-studio\tools\sdb.exe"
$tvQBC  = "192.168.1.11:26101"
$tvSBB  = "192.168.1.39:26101"
$appId  = "fmDBbBnvJM.NexariTizen"
$pi     = "chiho@192.168.1.17"
$tmp    = "$env:TEMP\nexari-tizen-build"

# ============================================================
# STEP 1: BUILD + PACKAGE (once, shared for both TVs)
# ============================================================
Write-Host "=== STEP 1: Build ==="

if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }
New-Item $tmp -ItemType Directory | Out-Null

$excludeNames = @(
    'node_modules', 'src', '.sign', '.settings',
    '.project', '.tproject', '.git',
    'vite.config.ts', 'package-lock.json', 'sssp_config.xml'
)
foreach ($item in Get-ChildItem $src) {
    if ($excludeNames -contains $item.Name) { continue }
    if ($item.Extension -eq '.wgt') { continue }
    if ($item.Name -eq '.manifest.tmp') { continue }
    if ($item.PSIsContainer) {
        Copy-Item $item.FullName "$tmp\$($item.Name)" -Recurse
    } else {
        Copy-Item $item.FullName $tmp
    }
}

Write-Host "Staging dir: $((Get-ChildItem $tmp -Recurse -File).Count) files"
Remove-Item "$src\*.wgt" -ErrorAction SilentlyContinue

# Run build:dev to regenerate build-info.js with LAN API URL (Pi at 192.168.1.17)
Write-Host "Running npm run build:dev..."
Push-Location $src
try {
    npm run build:dev 2>&1 | Write-Host
    if ($LASTEXITCODE -ne 0) { throw "npm run build:dev failed" }
} finally {
    Pop-Location
}

# Re-copy all compiled js/ output (regenerated by build:dev via tsc)
Copy-Item "$src\js" "$tmp\js" -Recurse -Force

Write-Host "Packaging with testforqbc profile..."
& $tizen package --type wgt --sign testforqbc -o $src -- $tmp 2>&1

$wgt = Get-ChildItem $src -Filter "*.wgt" | Select-Object -First 1
if (-not $wgt) {
    Write-Error "Build failed - no WGT produced. Aborting."
    exit 1
}
if ($wgt.Name -ne "NexariPlayer.wgt") {
    Rename-Item $wgt.FullName "$src\NexariPlayer.wgt" -Force
    Write-Host "Renamed $($wgt.Name) -> NexariPlayer.wgt"
}
$sizeKB = [math]::Round((Get-Item "$src\NexariPlayer.wgt").Length / 1KB)
Write-Host "WGT size: ${sizeKB} KB"

# Update sssp_config.xml with the exact byte-size
$wgtBytes   = (Get-Item "$src\NexariPlayer.wgt").Length
$ssspConfig = "$src\sssp_config.xml"
(Get-Content $ssspConfig -Raw) -replace '<size>\d+</size>', "<size>$wgtBytes</size>" |
    Set-Content $ssspConfig -NoNewline
Write-Host "Updated sssp_config.xml <size> to $wgtBytes bytes"

# ============================================================
# STEP 1c: DEPLOY TO PI SERVER
# ============================================================
Write-Host ""
Write-Host "=== STEP 1c: Deploy WGT to Pi server ($pi) ==="
$piTizenDir = "/var/signage/tizen"
scp "$src\NexariPlayer.wgt" "${pi}:${piTizenDir}/NexariPlayer.wgt"
if ($LASTEXITCODE -ne 0) { Write-Warning "WGT SCP failed - check SSH access to $pi" }
scp "$src\sssp_config.xml" "${pi}:${piTizenDir}/sssp_config.xml"
if ($LASTEXITCODE -ne 0) { Write-Warning "sssp_config.xml SCP failed" }
Write-Host "Pi server updated: http://192.168.1.17/tizen/NexariPlayer.wgt"

# ============================================================
# Helper function: connect, uninstall, install, launch one TV
# ============================================================
function Install-NexariOnTV {
    param([string]$tv, [string]$label)

    Write-Host ""
    Write-Host "======================================================"
    Write-Host "  TARGET: $label ($tv)"
    Write-Host "======================================================"

    # SDB CONNECT
    Write-Host ""
    Write-Host "--- SDB Connect ---"
    $connectOut = & $sdb connect $tv 2>&1 | Out-String
    Write-Host $connectOut
    if ($connectOut -notmatch "connected to|already connected") {
        Write-Host "WARNING: sdb connect may have failed for $label. Skipping." -ForegroundColor Yellow
        return
    }
    Start-Sleep -Seconds 2

    # UNINSTALL
    Write-Host ""
    Write-Host "--- Uninstall ---"
    foreach ($pkg in @($appId, "yhSyDyxfkq.NexariPlayer", "q6naPUaTRW.NexariPlayer")) {
        Write-Host "Removing $pkg ..."
        & $tizen uninstall -s $tv -p $pkg 2>&1 | Out-String | Write-Host
    }
    Start-Sleep -Seconds 3

    # INSTALL
    Write-Host ""
    Write-Host "--- Install ---"
    & $tizen install -s $tv -n NexariPlayer.wgt -- $src 2>&1

    # LAUNCH
    Write-Host ""
    Write-Host "--- Launch ---"
    Start-Sleep -Seconds 2
    & $tizen run -s $tv -p $appId 2>&1 | Out-String | Write-Host
}

# ============================================================
# STEP 2: DEPLOY TO QBC (192.168.1.11)
# ============================================================
Install-NexariOnTV -tv $tvQBC -label "QBC"

# ============================================================
# STEP 3: DEPLOY TO SBB TV (192.168.1.39)
# ============================================================
Install-NexariOnTV -tv $tvSBB -label "SBB TV"

Write-Host ""
Write-Host "=== All done. ===" -ForegroundColor Green