jobs:
  - name: local
    address: mqtt://192.168.1.17:1883
    username: test
    password: test1234
    topics:
      - topic: $SYS/broker/clients/connected
        name: clients_connected
      - topic: $SYS/broker/messages/received
        name: messages_received
      - topic: $SYS/broker/messages/sent
        name: messages_sent
      - topic: $SYS/broker/subscriptions/count
        name: subscriptions_count
      - topic: $SYS/broker/bytes/received
        name: bytes_received
      - topic: $SYS/broker/bytes/sent
        name: bytes_sent
