// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-build-info.cjs
(function () {
  var info = {
    version: "1.0.0",
    buildId: "20260412-194502Z",
    builtAt: "2026-04-12T19:45:02.092Z"
  };

  // Exposed for debugging in Remote Inspector
  window.PLAYER_BUILD_INFO = info;
  window.PLAYER_DEPLOY_VERSION = info.version + ' ' + info.buildId;
})();
